export const dataContent = [
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Aktif",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Tidak Aktif",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Menunggu",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Aktif",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Aktif",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Aktif",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Aktif",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Aktif",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Aktif",
    member: "1000",
  },
  {
    no: 1,
    groupName: "Komunitas Motor",
    groupType: "Perushaan",
    groupCreator: "Muh. Arifandi",
    username: "@motorindo",
    dateCreated: "24 Sep 2022",
    totalPost: "21 Post",
    status: "Aktif",
    member: "1000",
  },
];
