export const dataContent = [
  {
    no: 1,
    fullName: "All Fine Maulinaro",
    gender: "P",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 2,
    fullName: "All Fine Maulinaro",
    gender: "P",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 3,
    fullName: "All Fine Maulinaro",
    gender: "L",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 3,
    fullName: "All Fine Maulinaro",
    gender: "P",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 1,
    fullName: "All Fine Maulinaro",
    gender: "P",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 2,
    fullName: "All Fine Maulinaro",
    gender: "P",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 1,
    fullName: "All Fine Maulinaro",
    gender: "P",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 2,
    fullName: "All Fine Maulinaro",
    gender: "P",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 3,
    fullName: "All Fine Maulinaro",
    gender: "L",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
  {
    no: 3,
    fullName: "All Fine Maulinaro",
    gender: "P",
    city: "Yogyakarta",
    numberPhone: "+62-853-1654-7777",
    email: "maulinaro@yahoo.com",
    sector: "Pabrik Elektronik",
    age: "21 Thn",
    action: "Detail",
  },
];

export const message = [
  {
    img: "../../../assets/img/profile.svg",
    nickName: "Muh. Arifandi",
    message: "Selamat malam",
    time: "Hari ini pada 09:00 AM",
  },
  {
    img: "../../../assets/img/profile.svg",
    nickName: "Muh. Arifandi",
    message: "Selamat malam",
    time: "Hari ini pada 09:00 AM",
  },
  {
    img: "../../../assets/img/profile.svg",
    nickName: "Muh. Arifandi",
    message: "Selamat malam",
    time: "Hari ini pada 09:00 AM",
  },
];
