export const dataContent = [
  {
    no: 1,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Sudah Dikerjakan",
  },
  {
    no: 2,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Sedang Berjalan",
  },
  {
    no: 3,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Selesai",
  },
  {
    no: 4,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Sudah Dikerjakan",
  },
  {
    no: 5,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Sudah Dikerjakan",
  },
  {
    no: 6,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Selesai",
  },
  {
    no: 7,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Sedang Berjalan",
  },
  {
    no: 8,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Selesai",
  },
  {
    no: 9,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Sudah Dikerjakan",
  },
  {
    no: 10,
    projectName: "MONITORING PENYALURAN BLT BBM TAHAP 1",
    projectType: "Publik",
    projectCreator: "Muh. Arifandi",
    member: "1000",
    dateCreated: "24 Sep 2022",
    status: "Sedang Berjalan",
  },
];

export const dataTask = [
  {
    no: 1,
    title: "Membuat halaman utama grup",
    description: "Membuat halaman utama grup",
    officer: "Muh Arifandi",
    status: "Sudah Dikerjakan",
  },
  {
    no: 2,
    title: "Membuat halaman utama grup",
    description: "Membuat halaman utama grup",
    officer: "Muh Arifandi",
    status: "Sedang Berjalan",
  },
  {
    no: 3,
    title: "Membuat halaman utama grup",
    description: "Membuat halaman utama grup",
    officer: "Muh Arifandi",
    status: "Selesai",
  },
];
