export const ALL_USERS = "ALL_USERS";
export const SET_VALUE_GENDER = "SET_VALUE_GENDER";
export const SET_VALUE_AGE = "VALUE_AGE";
export const SET_VALUE_CITY = "VALUE_CITY";
export const SET_DROPDOWN_CITY = "SET_DROPDOWN_CITY";
export const SET_VALUE_STATUS = "SET_VALUE_STATUS";
export const SET_PAGINATION = "SET_PAGINATION";
