export const SET_DASHBOARD_GRUP = "SET_DASHBOARD_GRUP";
export const SET_ALL_GRUP = "ALL_GRUP";
export const SET_REQUEST_DETAIL_GRUP = "SET_REQUEST_DETAIL_GRUP";
export const SET_SEARCH_GRUP = "SET_SEARCH_GRUP";
export const SET_GRUP_DETAIL = "SET_GRUP_DETAIL";
export const SET_APPROVED = "SET_APPROVED";
export const SET_ACTION = "SET_ACTION";
